name: agora_token_generator
description: A Flutter package for generating Agora Dynamic Keys and Access Tokens for RTC and RTM services. Supports multiple token types including RTC tokens with UID/Account and RTM tokens.
version: 0.0.1
homepage: https://github.com/MohamedAbd0/Tools-Agora/tree/master/DynamicKey/AgoraDynamicKey/dart
repository: https://github.com/MohamedAbd0/Tools-Agora
issue_tracker: https://github.com/MohamedAbd0/Tools-Agora/issues

topics:
  - agora
  - token
  - rtc
  - rtm
  - authentication
environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.6
  convert: ^3.1.2
  pointycastle: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.8
